# Generated by Django 6.0.3 on 2026-03-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('img', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
    ]
